package com.statista.code.challenge.business;

import com.statista.code.challenge.persistence.BookingRepository;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Currency;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;

class BookingServiceTest {

    @Test
    void shouldSaveAndSendConfirmation() {
        NotificationService notificationService = mock(NotificationService.class);
        BookingRepository bookingRepository = mock(BookingRepository.class);
        when(bookingRepository.save(any())).thenReturn(
                Booking.builder()
                        .booking_id("generated by mock repo")
                        .description("masterplan")
                        .price(BigDecimal.valueOf(9.99))
                        .currency(Currency.getInstance("EUR"))
                        .email("'tis but a string")
                        .subscription_start_date(Instant.now())
                        .department("ministry of silly walks")
                        .build());
        BookingService bookingService = new BookingService(bookingRepository, notificationService);
        // Given the data for a Booking
        Booking booking = Booking.builder()
                .description("masterplan")
                .price(BigDecimal.valueOf(9.99))
                .currency(Currency.getInstance("EUR"))
                .email("'tis but a string")
                .subscription_start_date(Instant.now())
                .department("ministry of silly walks")
                .build();

        // When I create a Booking for it
        Booking createdBooking = bookingService.create(booking);

        // Then the Booking has an Id
        assertThat(createdBooking.booking_id()).isEqualTo("generated by mock repo");

        // And then a notification is sent
        verify(notificationService).send(createdBooking);
    }

    @Test
    void shouldUpdate() {
        NotificationService notificationService = mock(NotificationService.class);
        BookingRepository bookingRepository = mock(BookingRepository.class);
        Booking expected = Booking.builder()
                .booking_id("1")
                .description("updated masterplan")
                .price(BigDecimal.valueOf(99999.99))
                .currency(Currency.getInstance("EUR"))
                .email("'tis but a string")
                .subscription_start_date(Instant.ofEpochSecond(1))
                .department("ministry of silly walks")
                .build();
        when(bookingRepository.save(expected)).thenReturn(
                expected);
        BookingService bookingService = new BookingService(bookingRepository, notificationService);

        // Given the data for a Booking
        String booking_id = "1" ;
        Booking bookingInput = Booking.builder()
                .description("updated masterplan")
                .price(BigDecimal.valueOf(99999.99))
                .currency(Currency.getInstance("EUR"))
                .email("'tis but a string")
                .subscription_start_date(Instant.ofEpochSecond(1))
                .department("ministry of silly walks")
                .build();

        // When I update it
        Booking updatedBooking = bookingService.update(booking_id, bookingInput);

        // Then the booking is saved
        assertThat(updatedBooking).isEqualTo(expected);
    }

    @Test
    void shouldSearch() {
        BookingRepository bookingRepository = mock(BookingRepository.class);
        BookingService bookingService = new BookingService(bookingRepository, ignored -> {
        });
        // Given a saved Booking
        when(bookingRepository.findById("y")).thenReturn(Booking.builder()
                .booking_id("y")
                .build());

        // When I search for it
        Booking actual = bookingService.search("y");

        // Then it is found
        assertThat(actual.booking_id()).isEqualTo("y");
    }
}